apiVersion: v1
kind: Service
metadata:
  name: mentoria-k8s-service # Nome do serviço
spec:
  selector:
    app: mentoria-k8s
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 5000
  type: NodePort
